### ISSUE TITLE
Support Amazon Linux 2

### ISSUE THREAD

**Issue by nitrocode** [pre-commit/action#115]
Hi. It would be nice if there were steps on how to use this with Amazon Linux 2.

Thanks for a great github action!

**Comment by nitrocode** [comment]
@asottile thanks for your consideration.

**Comment by asottile** [comment]
sorry but if you read the README this is in maintenance only and I have no idea what "on amazon linux" would even mean -- this action doesn't do much and you can probably audit the code and make it work for your custom environment just as fast as I can.  and I'm not too keen on doing that for you for free without your company sponsoring my development -- so sorry but that's why I closed without comment

**Comment by nitrocode** [comment]
@asottile oh I see. No worries at all.

It might help to archive the repo but if that's not possible, maybe update the `README` to make the deprecation bigger and a note in the repo description? In any event, thanks for considering. I'll look into the alternative recommended in the `README`.
